font-size = 17
font-thicken = true
font-thicken-strength = 0
font-family = "psudoFont Liga Mono"

adjust-cell-height = 10

theme = "light:GitLab Light, dark:GitLab Dark"

macos-icon = "blueprint"
mouse-hide-while-typing = "true"

cursor-opacity = "0.8"
cursor-color = "cell-foreground"
cursor-invert-fg-bg = true

title = " "
macos-window-buttons = "hidden"
macos-titlebar-proxy-icon = "hidden"

minimum-contrast = 1.5

window-colorspace = "display-p3"
window-padding-balance = true
window-decoration = "none"
macos-titlebar-style = "hidden"
